In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets
from random import uniform 
from faker import Factory,Faker
from sklearn.preprocessing import normalize,MinMaxScaler
from pandas import to_datetime
from random import randint
import datetime as dt
%matplotlib inline

fake = Faker()

### 2. Build the real estate data table

In [7]:
import random

def random_coord(start, end):
    return round(random.uniform(start, end), 6)

real_estate_data = []
for i in range(100000):
    state = fake.state()
    city = fake.city()
    street_address = fake.street_address()
    real_estate = {
        'real_estate_id': i + 1,
        'real_estate_owner': fake.company(),
        'street_address': street_address,
        'business_name': fake.company(),
        'state': state,
        'zip_code': fake.zipcode(),
        'num_investors': fake.random_int(min=1, max=100),
        'cost': fake.random_int(min=100000, max=10000000) / 100,
        'building_type': fake.random_element(elements=('Residential', 'Commercial', 'Industrial')),
        'building_material': fake.random_element(elements=('Brick', 'Concrete', 'Steel', 'Wood')),
        'insured_value': fake.random_int(min=100000, max=10000000) / 100,
        'city' : city,
        'latitude' : random_coord(24.396308, 49.384358),
        'longitude' : random_coord(-125.000000, -66.934570)
    }
    real_estate_data.append(real_estate)

# Create a pandas DataFrame from the real estate data
real_estate_df = pd.DataFrame(real_estate_data)

real_estate_df.reset_index(inplace = True, drop = True)

real_estate_df.head(5)

,real_estate_id,real_estate_owner,street_address,business_name,state,zip_code,num_investors,cost,building_type,building_material,insured_value,city,latitude,longitude
0,1,Lucas LLC,487 Corey Route,Woodard and Sons,Wyoming,02428,45,87699.65,Commercial,Wood,43556.48,Phillipstad,24.674443,-99.324506
1,2,Humphrey-Moon,52174 Dwayne Flat,"Smith, Campbell and Reeves",Mississippi,53996,97,56268.65,Residential,Concrete,55180.05,Michaelfurt,32.324473,-73.225467
2,3,Mora Inc,509 James Point Suite 672,Castillo-West,Iowa,38466,45,11022.68,Commercial,Concrete,57312.36,Lake Tammy,41.103293,-101.088229
3,4,"Smith, Reid and Hill",904 Seth Crescent,Delgado-Walton,North Carolina,28267,78,85757.75,Commercial,Brick,40642.27,Seanborough,32.760149,-103.519233
4,5,Stanley and Sons,06225 Brandon Place,"Riggs, Black and Hernandez",Michigan,81475,84,24634.53,Industrial,Concrete,88505.41,Ashleyton,26.513110,-88.481312

In [8]:
real_estate_df.reset_index(inplace = True, drop = True)

In [9]:
real_estate_df.head(5)

,real_estate_id,real_estate_owner,street_address,business_name,state,zip_code,num_investors,cost,building_type,building_material,insured_value,city,latitude,longitude
0,1,Lucas LLC,487 Corey Route,Woodard and Sons,Wyoming,02428,45,87699.65,Commercial,Wood,43556.48,Phillipstad,24.674443,-99.324506
1,2,Humphrey-Moon,52174 Dwayne Flat,"Smith, Campbell and Reeves",Mississippi,53996,97,56268.65,Residential,Concrete,55180.05,Michaelfurt,32.324473,-73.225467
2,3,Mora Inc,509 James Point Suite 672,Castillo-West,Iowa,38466,45,11022.68,Commercial,Concrete,57312.36,Lake Tammy,41.103293,-101.088229
3,4,"Smith, Reid and Hill",904 Seth Crescent,Delgado-Walton,North Carolina,28267,78,85757.75,Commercial,Brick,40642.27,Seanborough,32.760149,-103.519233
4,5,Stanley and Sons,06225 Brandon Place,"Riggs, Black and Hernandez",Michigan,81475,84,24634.53,Industrial,Concrete,88505.41,Ashleyton,26.513110,-88.481312

In [10]:
real_estate_df.to_csv('datasets/fake_real_estate.csv')