In [5]:
import os, requests, time, json, glob
from io import StringIO
from datetime import date
from datetime import timedelta 
import matplotlib.pyplot as plt

import pandas as pd
import geopandas as gpd
#import h3pandas

from geoalchemy2 import Geometry, WKTElement
import psycopg2
from sqlalchemy import create_engine

from pandas import json_normalize
import urllib, urllib3, urllib.parse

In [ ]:
df = pd.read_csv('datasets/fake_real_estate.csv')

In [20]:
df.head(5)

,Unnamed: 0,real_estate_id,real_estate_owner,street_address,business_name,state,zip_code,num_investors,cost,building_type,building_material,insured_value,city,latitude,longitude
0,0,1,Hardin-Johnson,520 Gonzalez Canyon,"Kelley, Carter and Bass",New York,82411,42,99506.14,Industrial,Brick,57255.24,Reedland,-11.146982,114.809570
1,1,2,"Taylor, Hernandez and Hill",56147 Christian Trail,"Hudson, Hansen and Garza",Kentucky,75828,29,50316.71,Residential,Wood,28110.78,South Robert,-15.160265,133.957904
2,2,3,Cole-Spencer,04608 Price Club Apt. 938,Morrow Inc,Alabama,1963,44,75621.33,Residential,Wood,38882.34,New Davidstad,67.134105,129.557238
3,3,4,"Brown, Harvey and Cohen",915 Robinson Crossing,Mccoy-Jackson,Rhode Island,84569,47,66873.80,Residential,Concrete,38505.74,Kelseyville,24.604504,-37.375721
4,4,5,Peters Inc,23558 Carlson Greens Suite 969,Thomas Group,Minnesota,75556,94,75599.40,Industrial,Steel,92375.39,Arthurfurt,10.701648,-23.104486

In [29]:
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.longitude, df.latitude))

In [30]:
gdf.head(5)

,Unnamed: 0,real_estate_id,real_estate_owner,street_address,business_name,state,zip_code,num_investors,cost,building_type,building_material,insured_value,city,latitude,longitude,geometry
0,0,1,Hardin-Johnson,520 Gonzalez Canyon,"Kelley, Carter and Bass",New York,82411,42,99506.14,Industrial,Brick,57255.24,Reedland,-11.146982,114.809570,POINT (114.80957 -11.14698)
1,1,2,"Taylor, Hernandez and Hill",56147 Christian Trail,"Hudson, Hansen and Garza",Kentucky,75828,29,50316.71,Residential,Wood,28110.78,South Robert,-15.160265,133.957904,POINT (133.95790 -15.16027)
2,2,3,Cole-Spencer,04608 Price Club Apt. 938,Morrow Inc,Alabama,1963,44,75621.33,Residential,Wood,38882.34,New Davidstad,67.134105,129.557238,POINT (129.55724 67.13410)
3,3,4,"Brown, Harvey and Cohen",915 Robinson Crossing,Mccoy-Jackson,Rhode Island,84569,47,66873.80,Residential,Concrete,38505.74,Kelseyville,24.604504,-37.375721,POINT (-37.37572 24.60450)
4,4,5,Peters Inc,23558 Carlson Greens Suite 969,Thomas Group,Minnesota,75556,94,75599.40,Industrial,Steel,92375.39,Arthurfurt,10.701648,-23.104486,POINT (-23.10449 10.70165)

In [34]:
gdf.to_file('datasets/fake_real_estate.gpkg', driver='GPKG', layer='name')

/Users/ /miniforge3/envs/awesome/lib/python3.9/site-packages/geopandas/io/file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,